# 2023-09-16 Testing out helix after getting annoyed fussing with lua again
theme = "catppuccin_latte"
#theme = "catppuccin_macchiato"

[editor]
scroll-lines = 1
line-number = "relative"
cursorline = true
cursorcolumn = true
completion-trigger-len = 1
bufferline = "multiple"
color-modes = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true
character = ""
skip-levels = 1

[editor.statusline]
# miveon (reverse neovim)
left = ["position", "selections", "diagnostics"]
center = ["file-name", "file-modification-indicator", "version-control", "spacer", "file-encoding"]
right = ["mode", "spinner"]
mode.normal = "view"
mode.insert = "type"
mode.select = "grab"

[editor.lsp]
display-messages = true
display-inlay-hints = true

[editor.soft-wrap]
enable = true
wrap-indicator = "󱞩"

[keys.insert]
esc = ["collapse_selection", "normal_mode"]

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]

[keys.select]
esc = ["collapse_selection", "keep_primary_selection", "normal_mode"]
