[[language]]
name = "rust"
[language-server.rust-analyzer.config.check]
command = "clippy"

[[language]]
name = "sql"
scope = "source.sql"
injection-regex = "sql"
file-types = ["sql"]
language-server = { command = "sql-language-server", args = ["up", "--method", "stdio"] }

[[language]]
name = "toml"
formatter = { command = "taplo", args = ["fmt", "-"] }